services:
  
  portainer:
    image: portainer/portainer-ce:2.25.1
    container_name: Portainer-ce
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1024M'
        reservations:
          cpus: '1'
          memory: '512M'
    restart: always

  pgdb:
    image: postgres:17.2
    #image: postgresql:16.4-pgloader
    container_name: PostgreSQL
    environment:
      - POSTGRES_PASSWORD=Y6_kgkUs
      - POSTGRES_USER=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: '2048M'
        reservations:
          cpus: '2'
          memory: '1024M'
    networks:
      mstp:
        ipv4_address: 172.28.0.1

  pgadmin:
    image: dpage/pgadmin4:8.14
    container_name: pgAdmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.ru
      - PGADMIN_DEFAULT_PASSWORD=REwAmD9_
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: '1024M'
        reservations:
          cpus: '1'
          memory: '512M'
    depends_on:
      - pgdb
    restart: always
    networks:
      mstp:
        ipv4_address: 172.28.0.2

  msdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: MSSQL-Server
    volumes:
      - mssql_system:/var/opt/mssql
      - mssql_user:/var/opt/sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Z5sC_oou
      - MSSQL_PID=Standard
      - MSSQL_COLLATION=Cyrillic_General_CI_AS
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          cpus: '6'
          memory: '4096M'
        reservations:
          cpus: '2'
          memory: '2048M'
    restart: always
    networks:
      mstp:
        ipv4_address: 172.28.0.3

volumes:
  portainer_data:
    name: "Portainer-ce"
    external: true
  postgres_data:
    name: "PostgreSQL"
    external: true
  pgadmin_data:
    name: "pgAdmin4"
    external: true
  mssql_system:
    name: "MSSQL-System"
    external: true
  mssql_user:
    name: "MSSQL-Users"
    external: true

networks:
  mstp:
    name: "mstp Intranet"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254